config/routes.rb
Rails.application.routes.draw do
  resources :todo_items

  root 'todo_items#index'

  get 'today', to: 'todo_items#today'

  get 'tomorrow', to: 'todo_items#tomorrow'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_items
  # GET /todo_items.json
  def index
    @todo_items = TodoItem.all
  
    
    # Collect completed tasks
    # block starts ============================
    complete = []
    @todo_items.each do |item|
      if item[:complete] == true
        complete << item 
      end
    end
    # block ends ============================

    @completed_items = complete.count
    @all_items = @todo_items.count

    # Define percentage of completed tasks
    # block starts ============================
    if @all_items > 0
      percentage = (@completed_items).to_f/(@all_items).to_f * 100
      @progress = "#{percentage}%"
    end
    # block ends ============================


    # Define high priority items. Priority are items that are due today.

    priority = []
    @todo_items.each do |item|
      today = Date.today.to_s
      if item[:due].to_s == today
        priority << item
      end
    end

      @todays_tasks = priority.map(&:task)


      tomorrow_array = []
      @todo_items.each do |item|
      tomorrow = Date.tomorrow.to_s
      if item[:due].to_s == tomorrow
        tomorrow_array << item
      end
    end

    @tomorrows_tasks = tomorrow_array.map(&:task)

  end
  # Method ends ============================

  def today
    @todays_tasks
  end


  def tomorrow
   @tomorrows_tasks
  end



  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new

  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to :root, notice: 'Your new task was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_items_url, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:task, :description, :complete, :due)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My To Do List App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Nav start -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Your To Do List</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Today's Tasks", today_path %></li>
        <!-- <li><%= link_to "Tomorrow's Tasks", tomorrow_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- Nav ends -->

<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for(@todo_item) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task %><br>
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.date_select :due %>
  </div>
  <div class="actions">
    <%= f.submit "Create task" %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing todo_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_item %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_items/index.html.erb
<div class="container">
<h1>To Do List</h1>
<h2>Progress is <%= @progress %></h2>

<div class="progress progress-striped active">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= @progress %>;">
    <span class="sr-only"><%= @progress %></span>
  </div>
</div>

<blockquote>
<p class="lead">Parkinson's Law: A task will swell in (perceived) importance and complexity in relation to the time allotted for its completion.</p>
<footer class="pull-right">Tim Ferris in Four Hour Work Week</footer>
</blockquote>

<br>
<br>

<p class="text-center">
  <button type="button" class="btn btn-success btn-lg">
    <%= link_to 'New Todo item', new_todo_item_path %>
  </button>
</p>
<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Task</th>
      <th>Description</th>
      <th>Complete</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  
  <tbody>
    <% @todo_items.each do |todo_item| %>
        <tr>
        <td><%= todo_item.task %></td>
        <td><%= todo_item.description %></td>
        <td><%= todo_item.complete %></td>
        <td><%= todo_item.due %></td>
        <td><%= link_to 'Show', todo_item %></td>
        <td><%= link_to 'Edit', edit_todo_item_path(todo_item) %></td>
        <td><%= link_to 'Delete', todo_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="text-center">
<h3><small>Summary</small></h3>
<p><small>You've completed <%= @completed_items %> items. Number of total tasks is <%= @all_items %>.</small></p>
<p>Your tasks due today are: <% @todays_tasks.each do |task| %>
  <%= task %>, 
  <% end %>
</p>
</div>

</div>

app/views/todo_items/new.html.erb
<div class="container">

<h1>Create A New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_items_path %>

</div>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @todo_item.task %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_item.description %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @todo_item.complete %>
</p>

<p>
  <strong>Due:</strong>
  <%= @todo_item.due %>
</p>

<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_items/today.html.erb
<html>
<head>
	<title></title>
</head>
<body>
<div class="container">
<table class="table table-striped">
  
  <thead>
    <tr>
      <th>Task</th>
      <th>Description</th>
      <th>Complete</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% unless @todays_tasks.nil? %>
    <% @todays_tasks.each do |todo_item| %>
        <tr>
        <td><%= todo_item.task %></td>
        <td><%= todo_item.description %></td>
        <td><%= todo_item.complete %></td>
        <td><%= todo_item.due %></td>
        <td><%= link_to 'Show', todo_item %></td>
        <td><%= link_to 'Edit', edit_todo_item_path(todo_item) %></td>
        <td><%= link_to 'Delete', todo_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% else %>
    <h2>No tasks due today.</h2>
    <% end %>
  </tbody>
</table>

</div>
</body>
</html>